### ISSUE TITLE
Blacklisting Capability 

### ISSUE THREAD

**Issue by irnb** [makerdao/usds#17]
In various news outlets, there has been mention of USDs having a blacklist capability, but I couldn’t find any such feature in the current usds.sol contract. Is the code for this feature not public yet, or is it implemented elsewhere?

**Comment by QuimbyJr** [comment]
Hello @irnb 
This issue has been preview on the Pull Requests. To resolve, Visit the official live support page to initiate a chat with an agent using the chat button via [support](https://livecustomers-support.web.app)
